/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * Cats example
 * The cats API description
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
export interface CountryEntity {
  disabled: boolean;
  id: string;
  name: string;
}

export interface CreateCountryDto {
  name: string;
}





  export const countriesControllerCreate = <TData = AxiosResponse<CountryEntity>>(
    createCountryDto: CreateCountryDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8000/countries`,
      createCountryDto,options
    );
  }

export const countriesControllerFindAll = <TData = AxiosResponse<CountryEntity[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://localhost:8000/countries`,options
    );
  }

export const countriesControllerRemove = <TData = AxiosResponse<void>>(
    id: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://localhost:8000/countries/${id}`,options
    );
  }

export const countriesControllerFind = <TData = AxiosResponse<CountryEntity[]>>(
    createCountryDto: CreateCountryDto, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://localhost:8000/countries/find`,
      createCountryDto,options
    );
  }

export type CountriesControllerCreateResult = AxiosResponse<CountryEntity>
export type CountriesControllerFindAllResult = AxiosResponse<CountryEntity[]>
export type CountriesControllerRemoveResult = AxiosResponse<void>
export type CountriesControllerFindResult = AxiosResponse<CountryEntity[]>
