version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data

volumes:
  postgres_data:
  redis:
    driver: local
